#!/usr/bin/env bash
# Movie Chat — updater
# Manual:     bash update.sh  /  npm run update
# Auto (cron): bash update.sh --auto
set -e

AUTO=0
[[ "${1:-}" == "--auto" ]] && AUTO=1

# ── ensure npm is on PATH (cron strips PATH; handle nvm + Homebrew installs) ──
if ! command -v npm &>/dev/null; then
  # nvm
  [ -s "$HOME/.nvm/nvm.sh" ] && \. "$HOME/.nvm/nvm.sh"
fi
if ! command -v npm &>/dev/null; then
  # Homebrew – Apple Silicon
  [ -d "/opt/homebrew/bin" ] && export PATH="/opt/homebrew/bin:$PATH"
fi
if ! command -v npm &>/dev/null; then
  # Homebrew – Intel / Linux
  [ -d "/usr/local/bin" ] && export PATH="/usr/local/bin:$PATH"
fi
if ! command -v npm &>/dev/null; then
  error "npm not found — add it to PATH and re-run."
  exit 1
fi

# ── colours ──────────────────────────────────────────────────────────────────
BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
RESET='\033[0m'

info()    { echo -e "  ${GREEN}✓${RESET}  $*"; }
warn()    { echo -e "  ${YELLOW}!${RESET}  $*"; }
error()   { echo -e "  ${RED}✗${RESET}  $*" >&2; }
heading() { echo -e "\n${BOLD}$*${RESET}"; }
ask()     { echo -en "  ${BOLD}?${RESET}  $* "; }

# ── locate the install dir ────────────────────────────────────────────────────
if [ -f "$(pwd)/ecosystem.config.js" ]; then
  INSTALL_DIR="$(pwd)"
elif [ -f "$HOME/movie-chat/ecosystem.config.js" ]; then
  INSTALL_DIR="$HOME/movie-chat"
else
  error "Cannot find Movie Chat installation. Run this from inside the movie-chat folder."
  exit 1
fi

cd "$INSTALL_DIR"

# ── header ───────────────────────────────────────────────────────────────────
if [ "$AUTO" -eq 0 ]; then
  echo ""
  echo -e "${BOLD}  Movie Chat — update${RESET}"
  echo "  ─────────────────────────────────────────"
fi

# ── check for updates ─────────────────────────────────────────────────────────
git fetch --quiet

LOCAL=$(git rev-parse HEAD)
REMOTE=$(git rev-parse "@{u}" 2>/dev/null || echo "")

if [ -z "$REMOTE" ]; then
  warn "No remote tracking branch — cannot check for updates."
  exit 1
fi

if [ "$LOCAL" = "$REMOTE" ]; then
  info "Already up to date."
  [ "$AUTO" -eq 0 ] && echo ""
  exit 0
fi

COMMITS_BEHIND=$(git rev-list HEAD..@{u} --count)

if [ "$AUTO" -eq 0 ]; then
  echo ""
  echo "  ${COMMITS_BEHIND} update(s) available:"
  git log HEAD..@{u} --oneline --format="    • %s"
  echo ""
  ask "Install now? [Y/n]"
  read -r REPLY
  [[ "$REPLY" =~ ^[Nn]$ ]] && echo "  Cancelled." && echo "" && exit 0
  echo ""
else
  echo "[$(date '+%Y-%m-%d %H:%M')] ${COMMITS_BEHIND} update(s) found — updating..."
fi

# ── pull ──────────────────────────────────────────────────────────────────────
# package-lock.json is regenerated by npm install on the production machine and
# commonly drifts from the repo version, blocking git pull. Reset it (and any
# other generated files) to the upstream version before merging.
DIRTY=$(git status --porcelain)
if [ -n "$DIRTY" ]; then
  warn "Local changes detected — resetting generated files before update..."
  git checkout -- . 2>/dev/null || true
fi

git pull --quiet
info "Downloaded latest code"

# ── npm install (always — restores any deps removed by previous prune/update) ──
[ "$AUTO" -eq 0 ] && echo "  Installing dependencies..."
npm install --silent
info "Dependencies ready"

# ── build (always required for production mode) ───────────────────────────────
[ "$AUTO" -eq 0 ] && echo "  Building..."
npm run build --silent
info "Build complete"

# ── restart pm2 ───────────────────────────────────────────────────────────────
if command -v pm2 &>/dev/null && pm2 describe movie-chat &>/dev/null 2>&1; then
  pm2 restart movie-chat --silent
  info "App restarted"
else
  warn "pm2 not running — start with:  npm run build && npm run start"
fi

# ── done ──────────────────────────────────────────────────────────────────────
if [ "$AUTO" -eq 0 ]; then
  echo ""
  echo -e "  ${BOLD}${GREEN}Movie Chat updated successfully!${RESET}"
  echo ""
else
  echo "[$(date '+%Y-%m-%d %H:%M')] Update complete."
fi
